### ISSUE TITLE
The Luhn algorithm does not fit all

### ISSUE THREAD

**Issue by pqpo** [KingsMentor/Luhn#2]
for example：
6221730301002042987、4563512600991090527

**Comment by KingsMentor** [comment]
@pqpo  I will run a check and update shortly.

**Comment by KingsMentor** [comment]
@pqpo What card type is it ?

**Comment by pqpo** [comment]
It's not a credit card number,  http://www.2cha.com/bank/bank_cardNum_4563512600991090527.html

**Comment by KingsMentor** [comment]
It will only work on card number.
