### ISSUE TITLE
Crash: "This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead."

### ISSUE THREAD

**Issue by rave1502** [KingsMentor/Luhn#6]
"This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead."

Hi Nothing fancy here, just created one Activity from it loading the luhn activity. and getting the following error:
"This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead."

`
private void makePayment() {
        Luhn.startLuhn(this, new LuhnCallback() {
            @Override
            public void cardDetailsRetrieved(Context context, LuhnCard luhnCard, final LuhnCardVerifier luhnCardVerifier) {
                luhnCardVerifier.startProgress();
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        luhnCardVerifier.requestOTP(4);
                    }
                }, 2500);
            }

            @Override
            public void otpRetrieved(Context context, final LuhnCardVerifier luhnCardVerifier, String s) {
                luhnCardVerifier.startProgress();
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        luhnCardVerifier.onCardVerified(false, getString(R.string.verification_error), getString(R.string.verification_error));
                    }
                }, 2500);
            }

            @Override
            public void onFinished(boolean b) {
                Toast.makeText(PaymentActivity.this, "Payment received", Toast.LENGTH_SHORT).show();
            }
        }, R.style.CardLuhnStyle);
    }
`

**Comment by KingsMentor** [comment]
It appears the application theme already requires an actionbar.
I have looked at the code and performed a quick fix on `Luhn`

Here's what `Luhn's` manifest look like before 

```xml
        <activity
            android:name=".Luhn"
            android:label="@string/add_card"
            android:windowSoftInputMode="adjustResize" />
```

Here is what I have changed it to 

```xml
        <activity
            android:name=".Luhn"
            android:label="@string/add_card"
            android:theme="@style/AppTheme.NoActionBar"
            android:windowSoftInputMode="adjustResize" />
```
A quick fix for you will be to make sure your application theme uses a theme that`windowActionBar` is false. (Requires `NoActionBar`)

Here's is how you can achieve that in `styles.xml`:

```xml
    <style name="AppTheme.NoActionBar" parent="AppTheme">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>
```

the next release will have this patch in it. Thanks.

**Comment by KingsMentor** [comment]
@rave1502 let me know if this fix has worked for you.

**Comment by rave1502** [comment]
Hi,
Thanks for your quick response.

My apologies, I am not very well verse with this part of android development. However, this is how my styles.xml look like (from the app module).

```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>
    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />
    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />
</resources>
```
So here, I think that the setting is already in place.

However, I would like to add my application is divided in multiple modules, where one of the module is using your card library. Here is the style.xml from the sub-module

```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
    <style name="CardLuhnStyle">
        <item name="luhn_title">Card Information</item>
        <item name="luhn_typeface">fonts/ClanMedium.ttf</item>
        <item name="luhn_btn_verify_selector">@drawable/card_next_btn_selector</item>
        <item name="luhn_show_toolbar_color">@color/colorAccent</item>
        <item name="luhn_show_pin">false</item>
    </style>
</resources>
```

I tried to tried to update both styles.xml files, but couldn't get pass through. I am still seeing the same issue. I guess, I need to wait until you release your patch.

**Comment by KingsMentor** [comment]
@rave1502 before I draft a new release, kindly use this on your `build.gradle`

`compile 'com.github.KingsMentor:Luhn:ff7856d5b6'`

this build is a patch for this issue.

**Comment by rave1502** [comment]
Thanks @KingsMentor it is working like a charm now. Your support is much appreciated.

**Comment by am9072** [comment]
There are **two simple and quick solutions**

go to res-->values-->styles
watch the simple video for the answer
[https://youtu.be/YJR8njVHRA4](url)

You can  remove your window action bar by setting NoActionBar 
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`
or by adding  <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>

**Comment by TanishqPokharia** [comment]
I have a divider between by recycler view items which loses its color set in an xml file due to android:theme="@style/Theme.Design.NoActionBar is there any solution to this?
