### ISSUE TITLE
request you to add card holder's Name & Phone number field

### ISSUE THREAD

**Issue by rave1502** [KingsMentor/Luhn#7]
In my country, it is expected to capture the card holder's name and phone number along with card details. Is there a way, we can add these fields to the layout?

Thanks,

**Comment by KingsMentor** [comment]
@rave1502 Luhn does not have that feature yet. To achieve this, you will have to clone the project and customize it to suite your requirements.

**Comment by rave1502** [comment]
Thanks @KingsMentor I will do the same.
