### ISSUE TITLE
i have used your project as a library project and not as build.gradle compile library

### ISSUE THREAD

**Issue by gauravarora90** [KingsMentor/Luhn#8]
My size of apk has increased a lot. Is it because of bundling or do you have some smaller versions of  your library available. ?

Do you have any proguard configurations for shrinking the resources ? I have found a lib folder in .apk file which has in turn .so files. Is there any way to ignore them.

**Comment by KingsMentor** [comment]
@gauravarora90  the library has *card.io* as a dependency.
This add a size of about 13mb to the apk size. I am currently looking into this. 
One Option we have is to have a Luhn that doesn't depend on `card.io`. I am also taking a look at Mobile Vision Api OCR Reader and I am working towards building a card.io functionality around it. I strongly believe the result will be a better and faster tool.

**Comment by gauravarora90** [comment]
Till then any options to reduce the apk size ?

**Comment by KingsMentor** [comment]
The apk can be splitted based on the architecture if multiple apks should be uploaded to the Google Play Store. Google Play Store manages to deliver the appropriate apk for the device. 
```xml
splits {
	abi {
		enable true
		reset()
		include "armeabi","armeabi-v7a","arm64-v8a","mips","mips64","x86","x86_64"
		universalApk false
	}
}
```
