### ISSUE TITLE
How can i hide pin request and start activity with default card values?

### ISSUE THREAD

**Issue by andres934** [KingsMentor/Luhn#9]
i have been using your library but in this case i don't need pin and also i need to edit cards information, so starting activity with default values to edit, is there a CardIOActivity value to disable pin and send default card information to activity?

**Comment by KingsMentor** [comment]
Add this to your LuhnStyle to hide the pin field

`<attr name="luhn_show_pin" format="boolean" />`

There is no option to prefill any field at the moment. This will be looked into and possibly released alongside the next update. You can also contribute by adding this feature and sending in a pull request. 

Thanks.

**Comment by andres934** [comment]
oh great thank you, by the way how should i fill the card information to get a success response from it? i always get error so never enter onFinished

**Comment by akiligedeon** [comment]
Good stuff. Am new to android, but how do i get card information?
